<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>MarsArmories.ImperialDate</Title>
    <Description>A .NET implementation of the 40k Imperial date similar to DateTime.</Description>
    <Authors>MarsArmories</Authors>
    <PackageProjectUrl>https://github.com/MarsArmories/ImperialDate</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MarsArmories/ImperialDate.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591;CS1570;CS1572;CS1573;CS1574;CS1584;CS1658</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../CHANGELOG.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
  </ItemGroup>

</Project>
