name: Deploy To Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    env:
      solution:  src/MarsArmories.ImperialDate.sln

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Restore dependencies
      run: dotnet restore $solution
    - name: Build
      run: dotnet build --no-restore $solution
    - name: Test
      run: dotnet test --no-build --verbosity normal $solution
    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/MarsArmories.ImperialDate/MarsArmories.ImperialDate.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        VERSION_REGEX: <PackageVersion>(.*)<\/PackageVersion>
        INCLUDE_SYMBOLS: true
    - name: Pack
      run: dotnet pack --no-build --configuration Release src/MarsArmories.ImperialDate/MarsArmories.ImperialDate.csproj --output .
    - name: Publish to Github
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
